project:
  type: website

website:
  title: "klogr"
  favicon: my_8bit_mush_circle.ico
  site-url: https://klogr.netlify.app/
  description: This is Kurtisâ€™ blog, klog for short. It serves to document my personal R related projects and to detail general data science issues Iâ€™ve journeyed the internet for and donâ€™t want to forget. In short, Iâ€™m using this site to unKlog my headspace ğŸ™†ğŸ½â€â™‚ï¸. Inspired by new technology / analysis and the exploration of its value ğŸ‘¾.
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-3VDFEKMNJY"
    anonymize-ip: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/KurtisAsha
      - icon: kaggle
        text: K
        href: https://www.kaggle.com/kurtissmith
      - icon: linkedin
        href: https://www.linkedin.com/in/kurtisashasmith/
      - icon: rss
        href: index.xml
format:
  html:
    theme: paper
    css: styles.css

editor: visual

